#ifndef SPREADSHEET_INCORRECT_FORMULA_SYNTAX_EXCEPTION_H
#define SPREADSHEET_INCORRECT_FORMULA_SYNTAX_EXCEPTION_H

#include "Exception.h"

class IncorrectFormulaSyntaxException : public Exception
{
};

#endif /* SPREADSHEET_INCORRECT_FORMULA_SYNTAX_EXCEPTION_H */
